- lib/src/widgets/comment/comment_tile.dart
- lib/src/widgets/comment/reply_tile.dart
- lib/src/widgets/common/profile_picture.dart
- lib/src/widgets/common/text/text_input.dart
- lib/src/widgets/post/post_header.dart
- Added line limit in comment text input ( 4 lines )
- Added expandable text in comment and reply tile
- Added tap listener in Profile Picture
> Release v1.0.3

- lib/src/widgets/comment/comment_tile.dart
- lib/src/widgets/post/post_media.dart
- Fixed comment ui issue
- Fixed post aspect ratio issue
> [LM-9489] Fixed UI issues

- lib/src/widgets/common/buttons/text_button.dart
- lib/src/widgets/common/profile_picture.dart
- lib/src/widgets/common/text/text_view.dart
- lib/src/widgets/post/post_header.dart
- pubspec.yaml
**Features**
**Bugs**
- added on tap on user name
> [LM-9671] Feed bugs and UI issues

- example/pubspec.yaml
- pubspec.yaml
**Features**
**Bugs**
- added additional parameters to UI elements
> Version update v1.1.1

- example/ios/Podfile.lock
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- example/pubspec.yaml
- lib/src/utils/utils.dart
- lib/src/widgets/common/buttons/text_button.dart
- lib/src/widgets/common/profile_picture.dart
- lib/src/widgets/common/text/text_view.dart
- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/image.dart
- lib/src/widgets/media/video.dart
- lib/src/widgets/post/post_header.dart
- lib/src/widgets/post/post_media.dart
- pubspec.lock
- pubspec.yaml
**Features**
- added additional parameters for ui styling
**Bugs**
> Release v1.1.1

- lib/packages/expandable_text/expandable_text.dart
- lib/src/widgets/common/shimmer/post_shimmer.dart
- lib/src/widgets/common/text/text_view.dart
- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/image.dart
- lib/src/widgets/post/post_header.dart
**Features**
**Bugs**
-Copy feature to replace edit feature [Done]
-User need to be taken to a profile when they click the general area where the name and Username is present (general area is highlights in the attached SS)  [Done]
-Post composer area has been cut down [Done]
-Topic selection has become optional [Done]
-All 5 topics should show up when selecting topic in the post composer (currently only 4 are showing) [Done]
-Topic filter shouldn't stick to the top when scrolling down. It can appear when you are scrolling back up [Done]
-Topic list is floating on screen [Done]
-Black screen loads first while using carousel [Done]
-Remove route to profile from tagging list [Done]
<p></p>
> [LM-9755] Feed bugs and ui issues

- example/pubspec.yaml
- pubspec.yaml
-Version change to v1.1.2
**Features**
**Bugs**
> Version v1.1.2

- example/pubspec.yaml
- lib/packages/expandable_text/expandable_text.dart
- lib/src/widgets/common/shimmer/post_shimmer.dart
- lib/src/widgets/common/text/text_view.dart
- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/image.dart
- lib/src/widgets/post/post_header.dart
- pubspec.yaml
**Features**
**Bugs**
-Copy feature to replace edit feature [Done]
-User need to be taken to a profile when they click the general area where the name and Username is present (general area is highlights in the attached SS) [Done]
-Post composer area has been cut down [Done]
-Topic selection has become optional [Done]
-All 5 topics should show up when selecting topic in the post composer (currently only 4 are showing) [Done]
-Topic filter shouldn't stick to the top when scrolling down. It can appear when you are scrolling back up [Done]
-Topic list is floating on screen [Done]
-Black screen loads first while using carousel [Done]
-Remove route to profile from tagging list [Done]
> Hotfix v1.1.2

- example/lib/views/new_post/new_post_screen.dart
- example/lib/views/post_detail/post_detail_screen.dart
- lib/packages/expandable_text/expandable_text.dart
- lib/src/utils/constants.dart
- lib/src/widgets/comment/comment_tile.dart
- lib/src/widgets/comment/reply_tile.dart
- lib/src/widgets/common/buttons/icon_button.dart
- lib/src/widgets/common/buttons/text_button.dart
- lib/src/widgets/common/icon/icon.dart
- lib/src/widgets/common/profile_picture.dart
- lib/src/widgets/common/shimmer/feed_shimmer.dart
- lib/src/widgets/common/shimmer/post_shimmer.dart
- lib/src/widgets/common/text/text_view.dart
- lib/src/widgets/feed/bottom_sheet.dart
- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/document.dart
- lib/src/widgets/media/image.dart
- lib/src/widgets/media/link.dart
- lib/src/widgets/media/video.dart
- lib/src/widgets/post/post_content.dart
- lib/src/widgets/post/post_header.dart
- lib/src/widgets/post/post_media.dart
- lib/src/widgets/topic/topic_chip.dart
- lib/src/widgets/widgets.dart
- pubspec.lock
> [LM-9777] added customisation in widgets

- example/lib/views/new_post/new_post_screen.dart
- example/lib/views/post_detail/post_detail_screen.dart
- lib/packages/expandable_text/expandable_text.dart
- lib/src/utils/constants.dart
- lib/src/widgets/comment/comment_tile.dart
- lib/src/widgets/comment/reply_tile.dart
- lib/src/widgets/common/buttons/icon_button.dart
- lib/src/widgets/common/buttons/text_button.dart
- lib/src/widgets/common/icon/icon.dart
- lib/src/widgets/common/profile_picture.dart
- lib/src/widgets/common/shimmer/feed_shimmer.dart
- lib/src/widgets/common/shimmer/post_shimmer.dart
- lib/src/widgets/common/text/text_view.dart
- lib/src/widgets/feed/bottom_sheet.dart
- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/document.dart
- lib/src/widgets/media/image.dart
- lib/src/widgets/media/link.dart
- lib/src/widgets/media/video.dart
- lib/src/widgets/post/post_content.dart
- lib/src/widgets/post/post_header.dart
- lib/src/widgets/post/post_media.dart
- lib/src/widgets/topic/topic_chip.dart
- lib/src/widgets/widgets.dart
- pubspec.lock
> Release v1.2.0

- example/pubspec.yaml
- pubspec.yaml
> Update Version to 1.2.0

- example/pubspec.yaml
- pubspec.yaml
**Features**
- Version update v1.3.0
**Bugs**
> Version update v1.3.0

- example/pubspec.yaml
- lib/src/widgets/post/post_header.dart
- lib/src/widgets/post/post_menu.dart
- pubspec.yaml
**Features**
- added customisation in post menu
**Bugs**
> Release v1.3.0

- lib/src/models/media_model.dart
- lib/src/widgets/comment/comment_tile.dart
- lib/src/widgets/comment/reply_tile.dart
- lib/src/widgets/media/document.dart
- lib/src/widgets/post/post_media.dart
**Features**
- added stylings fixes
**Bugs**
> [LM-9996] added styling fixes

- lib/src/widgets/comment/comment_tile.dart
- lib/src/widgets/comment/reply_tile.dart
- lib/src/widgets/post/post_content.dart
**Features**
- adding customisation for link and tag color
**Bugs**
> [LM-10008] added support for link and tag color customisation

- example/pubspec.yaml
- pubspec.yaml
**Features**
- Version update to v1.3.2
**Bugs**
> Version update to v1.3.2

- lib/src/widgets/post/post.dart
- lib/src/widgets/post/post_media.dart
- pubspec.yaml
**Features**
**Bugs**
- Empty space was shown in case custom widget was there in the post
> fixed empty attachment issue

- example/pubspec.yaml
- pubspec.yaml
**Features**
- version update to v1.3.3
**Bugs**
> Version v1.3.3

- example/pubspec.yaml
- lib/packages/expandable_text/expandable_text.dart
- lib/src/widgets/post/post.dart
- lib/src/widgets/post/post_media.dart
- pubspec.yaml
**Features**
- fixed empty attachment issue
**Bugs**
> Release v1.3.3

- example/pubspec.yaml
- lib/src/widgets/common/extras/loader.dart
- pubspec.yaml
**Features**
- added color support in LMLoader
**Bugs**
> LM-10093 added color support in LMLoader

- example/pubspec.yaml
- pubspec.yaml
**Features**
- version update to v1.3.4
**Bugs**
> version update to v1.3.4

- example/pubspec.yaml
- pubspec.yaml
**Features**
- update sdk version
**Bugs**
> Update sdk version v1.3.5

- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/video.dart
- lib/src/widgets/post/post_content.dart
- lib/src/widgets/post/post_media.dart
- pubspec.lock
- pubspec.yaml
**Features**
- added video support
**Bugs**
> LM-10126 lm video

- example/pubspec.yaml
- pubspec.yaml
Updating version for release
**Features**
**Bugs**
> Version update v1.3.5

- example/lib/views/feed/feed_page.dart
- example/lib/views/post_detail/post_detail_screen.dart
- lib/likeminds_feed_ui_fl.dart
- lib/packages/expandable_text/expandable_text.dart
- lib/packages/linkify/linkify.dart
- lib/packages/linkify/src/email.dart
- lib/packages/linkify/src/url.dart
- lib/src/models/models.dart
- lib/src/models/post_ui.dart
- lib/src/utils/constants.dart
- lib/src/utils/helpers.dart
- lib/src/widgets/common/extras/loader.dart
- lib/src/widgets/post/post.dart
- pubspec.yaml
Fixed Link Regex
**Features**
**Bugs**
> [LM-10063] Link Regex

- example/pubspec.yaml
- pubspec.yaml
**Features**
- Version update to v1.3.7
**Bugs**
> Version update to v1.3.7

- lib/src/widgets/media/carousel.dart
- lib/src/widgets/media/video.dart
- lib/src/widgets/post/post_media.dart
- pubspec.lock
- pubspec.yaml
**Features**
- added callback for video controller
**Bugs** 
> LM-10271 added callback for VideoController

- example/pubspec.yaml
- pubspec.yaml
**Features**
**Bugs**
- Added a callback in LMVideo
> chore(Version): update to v1.3.8

- lib/src/widgets/media/carousel.dart
- lib/src/widgets/post/post_media.dart
Fixed center alignment for LMVideo and add background color for LMImage
**Features**
**Bugs**
> [LM-10347] Fixed LMVideo alignment

- lib/src/widgets/post/post_header.dart
**Features**
**Bugs**
-  Fixed spacing and dot icon in post header
> [LM-10084] UI issues fix

- pubspec.yaml
**Features**
**Bugs**
- Fix video codec issue in Android
> fix(Video): flutter version decrease to fix video codec

- example/pubspec.yaml
- pubspec.yaml
**Features**
-  Version change For user activity support
**Bugs**
> [LM-10594] Version change For user activity support

- example/lib/views/new_post/new_post_screen.dart
- example/pubspec.yaml
- lib/src/models/models.dart
- lib/src/models/post_attachment_ui.dart
- lib/src/models/post_ui.dart
- lib/src/widgets/media/link.dart
- pubspec.lock
- pubspec.yaml
**Features**
- Added support for repost api
**Bugs**
> [LM-10489] Repost

- example/pubspec.yaml
- pubspec.yaml
> chore: version update
